
services:

  user_management:
    image: node
    container_name: user_management
    build: 
      context: ./backend/userConf
    ports:
      - 3000:3000
    volumes:
      - ./backend/:/backend/:rw #Vai guardar na home 
    networks:
      - ft_transcendence


networks:
  ft_transcendence:
    name: ft_transcendence
    driver: bridge