
services:

  user_management:
    image: user_management
    container_name: user_management
    build: 
      context: ./backend/user/conf
    ports:
      - 3000:3000
    volumes:
      - ./backend/:/backend/:rw #Vai guardar na home 
    networks:
      - ft_transcendence

  game:
    image: pongify
    container_name: pongify
    environment:
      - NODE_ENV=PRODUCTION
    volumes:
      - ./game-project:/pong_vol/game-project/:rw
      - sqlite_data:/pong_vol/game-project/database.sqlite # add
    ports:
      - "5000:5000"
    build: ./game-project/
    networks:
      - ft_transcendence

  gateway:
    image: gateway-api
    container_name: gateway-api
    build: 
      context: ./backend/Gateway/config
    ports:
      - 7000:7000
    volumes:
      - ./backend/Gateway:/backend/:rw #Vai guardar na home 
    networks:
      - ft_transcendence

networks:
  ft_transcendence:
    name: ft_transcendence
    driver: bridge

volumes:
  sqlite_data: