
services:

  dataBase:
    # psql -h localhost -p 5432 -U aleperei -d transcendence 
    image: postgres
    container_name: dataBase
    shm_size: 128mb
    env_file:
      - .env
    # environment:
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_USER: ${POSTGRES_USER} 
    #   POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - ft_transcendence
    expose:
      - 5432

  django:
    image: python
    container_name: djangoTraining
    env_file:
      - .env
    depends_on:
      dataBase:
        condition: service_started
    build: 
      context: ./conf
    ports:
      - "8000:8000"
    volumes:
      - ./teste1:/teste1:rw #Vai guardar na home
    networks:
      - ft_transcendence


networks:
  ft_transcendence:
    name: ft_transcendence
    driver: bridge