version: '3.8'
services:
  pong-game:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - game-network

networks:
  game-network:
    driver: bridge
