# NODE_MODULES = node_modules

# all: build up

# build:
# 	@echo "Building all Docker images..."
# 	docker compose build

# up:
# 	@echo "Starting all containers..."
# 	docker compose up

# down:
# 	@echo "Stopping all containers..."
# 	docker compose down

# clean: down
# 	@echo "🗑 Cleaning up..."
# 	rm -rf server.js public/menu.js public/game.js
# 	rm -rf $(NODE_MODULES)

# recomp: down
# 	docker rmi pongify
# # docker network rm net_pong
# 	docker compose build
# 	docker compose up

