# Generated by Django 5.1.4 on 2025-01-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('apelido', models.CharField(max_length=100)),
                ('idade', models.IntegerField(default=0)),
            ],
        ),
    ]
